# Generated by Django 4.2.6 on 2023-11-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gems',
            field=models.IntegerField(default=0),
        ),
    ]
